### ISSUE TITLE
Metrics incorrectly reports not live

### ISSUE THREAD

**Issue by camdenfullmer** [boxcast/boxcast-sdk-tvos#1]
The comparison here (https://github.com/boxcast/boxcast-sdk-tvos/blob/master/src/BoxCastPlayerMetrics.js#L123) checks to see if the status is "live", but what happens if the status is `stalled` or another status that is only part of a live view? Wouldn't that incorrectly report that the metric isn't part of the live view?

**Comment by bikegriffith** [comment]
We should definitely test this, as well as with the boxcast/boxcast_js player.  The analytics service only initializes the is_live flag once, so it could lead to misattributed live vs recorded entries.  We should also confirm what happens if user comes during preroll period and stays to watch live without refreshing page.
